### ISSUE TITLE
Entering incorrect password in console docker container crashes it

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti-console#30]
At the ZAC web GUI login screen, enter any password for admin (in this case), it may be other accounts and the docker container quits/crashes, and needs to be restarted.  Enter the correct password, and the console works fine.

Looking at the log, I get this

```
/usr/src/app/server.js:194
					if (body.error) response.json( {error: body.error.message} );
					                ^

ReferenceError: response is not defined
    at Request._callback (/usr/src/app/server.js:194:22)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by JeremyTellier** [comment]
Oops, I fixed the ZAC console and pushed it up to the branch. New Docker Image coming soon I imagine. Thanks!
