### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by tczee36** [openziti/ziti-console#38]
hello,

your aws hosting server is down? or is there some other issue?

```
node-pre-gyp ERR! install response status 403 Forbidden on https://ziti-npm.s3.amazonaws.com/ziti_sdk_nodejs/v0.9.2/Release/ziti_sdk_nodejs-v0.9.2-node-v64-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for @openziti/ziti-sdk-nodejs@0.9.2 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 403 Forbidden on https://ziti-npm.s3.amazonaws.com/ziti_sdk_nodejs/v0.9.2/Release/ziti_sdk_nodejs-v0.9.2-node-v64-linux-x64.tar.gz
make: Entering directory '/home/ziti/.ziti/quickstart/ubuntu-s-2vcpu-4gb-sfo3-01/ziti-console/node_modules/@openziti/ziti-sdk-nodejs/build'
  CC(target) Release/obj.target/ziti_sdk_nodejs/src/ziti-add-on.o
In file included from ../src/ziti-add-on.c:17:
../src/ziti-nodejs.h:23:10: fatal error: uv_mbed/uv_mbed.h: No such file or directory
   23 | #include <uv_mbed/uv_mbed.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [ziti_sdk_nodejs.target.mk:144: Release/obj.target/ziti_sdk_nodejs/src/ziti-add-on.o] Error 1
make: Leaving directory '/home/ziti/.ziti/quickstart/ubuntu-s-2vcpu-4gb-sfo3-01/ziti-console/node_modules/@openziti/ziti-sdk-nodejs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-121-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--fallback-to-build" "--module=/home/ziti/.ziti/quickstart/ubuntu-s-2vcpu-4gb-sfo3-01/ziti-console/node_modules/@openziti/ziti-sdk-nodejs/build/Release/node-v64-linux-x64/ziti_sdk_nodejs.node" "--module_name=ziti_sdk_nodejs" "--module_path=/home/ziti/.ziti/quickstart/ubuntu-s-2vcpu-4gb-sfo3-01/ziti-console/node_modules/@openziti/ziti-sdk-nodejs/build/Release/node-v64-linux-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"


```

**Comment by dovholuknf** [comment]
yikes - this has been open for a long time and nobody commented! I think we fixed this back around when you reported this. I'm closing this issue now, but if you still have problems please reopen and thank you for reporting it
